// TODO: 백엔드 팀 API 연동되면 아래 mock 제거하고 axiosInstance.get(...) 호출로 교체
const MOCK_COACHING_HISTORY = [
  {
    id: 1,
    fileName: "김레주_이력서_최종.pdf",
    type: "resume",
    status: "inProgress",
    summary: "AI가 자기소개서 표현과 성과 중심 서술을 보완하고 있어요.",
    date: "2026.03.12",
    step: 2,
    totalSteps: 3,
    progress: 56,
  },
  {
    id: 2,
    fileName: "김레주_자소서_초안.docx",
    type: "coverletter",
    status: "completed",
    summary: "3가지 개선 포인트와 모범 답변 예시를 제공했어요. 최종 수정에 반영해 보세요.",
    date: "2026.03.08",
    issueCount: 23,
    grade: "A-",
  },
  {
    id: 3,
    fileName: "김레주_이력서_v2.pdf",
    type: "resume",
    status: "completed",
    summary: "직무 경험을 성과 중심으로 재구성했어요. 면접 예상 질문도 함께 확인하세요.",
    date: "2026.02.20",
    issueCount: 17,
    grade: "B+",
  },
  {
    id: 4,
    fileName: "김레주_자소서_1차.docx",
    type: "coverletter",
    status: "completed",
    summary: "지원 동기와 입사 후 포부 항목을 구체적으로 보완했어요.",
    date: "2026.02.14",
    issueCount: 11,
    grade: "B",
  },
  {
    id: 5,
    fileName: "김레주_이력서_초안.pdf",
    type: "resume",
    status: "completed",
    summary: "핵심 역량 키워드를 상단에 배치하도록 구조를 개선했어요.",
    date: "2026.01.30",
    issueCount: 15,
    grade: "B+",
  },
  {
    id: 6,
    fileName: "김레주_자소서_2차.docx",
    type: "coverletter",
    status: "completed",
    summary: "직무 연관 경험 위주로 문단 순서를 재배치했어요.",
    date: "2026.01.22",
    issueCount: 9,
    grade: "A-",
  },
  {
    id: 7,
    fileName: "김레주_이력서_영문.pdf",
    type: "resume",
    status: "completed",
    summary: "해외 채용 관행에 맞춰 표현과 형식을 다듬었어요.",
    date: "2026.01.10",
    issueCount: 20,
    grade: "B",
  },
  {
    id: 8,
    fileName: "김레주_자소서_최종.docx",
    type: "coverletter",
    status: "completed",
    summary: "전체 분량을 조정하고 문장 호응 오류를 수정했어요.",
    date: "2025.12.28",
    issueCount: 6,
    grade: "A",
  },
];

export const getCoachingHistory = async () => {
  return MOCK_COACHING_HISTORY; // [{ id, fileName, type, status, summary, date, step?, totalSteps?, progress?, issueCount?, grade? }]
};
